# Generated by Django 3.2.7 on 2021-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Product Logo')),
                ('model', models.CharField(max_length=100, verbose_name='Model Name')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Size (in inches)')),
                ('frame', models.CharField(max_length=100, verbose_name='Frame')),
            ],
        ),
    ]
