# Generated by Django 3.2.7 on 2021-10-05 09:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title of Event')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Event Description')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='Link of Event')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Event Image')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Image/Event Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description of the Event/Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Main Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='amazonlink',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Amazon Link'),
        ),
        migrations.AddField(
            model_name='product',
            name='bottombracket',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Bottom Bracket'),
        ),
        migrations.AddField(
            model_name='product',
            name='chain',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Chain'),
        ),
        migrations.AddField(
            model_name='product',
            name='decal',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Decal'),
        ),
        migrations.AddField(
            model_name='product',
            name='fderaileur',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Front Deraileur'),
        ),
        migrations.AddField(
            model_name='product',
            name='fork',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fork'),
        ),
        migrations.AddField(
            model_name='product',
            name='handlebar',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Handle Bar'),
        ),
        migrations.AddField(
            model_name='product',
            name='headset',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Headset'),
        ),
        migrations.AddField(
            model_name='product',
            name='pedal',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Pedal'),
        ),
        migrations.AddField(
            model_name='product',
            name='rderaileur',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Rear Deraileur'),
        ),
        migrations.AddField(
            model_name='product',
            name='rims',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Rims'),
        ),
        migrations.AddField(
            model_name='product',
            name='saddle',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Saddle'),
        ),
        migrations.AddField(
            model_name='product',
            name='shifter',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Shifter'),
        ),
        migrations.AddField(
            model_name='product',
            name='stem',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Stem'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Tube'),
        ),
        migrations.AddField(
            model_name='product',
            name='tyre',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Tyre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frame'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Size (in inches)')),
                ('of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.product')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=50, verbose_name='Color Variant Name')),
                ('color', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors', verbose_name='Color Variant Image')),
                ('of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.product')),
            ],
        ),
    ]
