# Generated by Django 3.2.7 on 2021-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Price in Rupees'),
        ),
    ]
